### ISSUE TITLE
C4 library doesn't work with !pragma layout smetana

### ISSUE THREAD

**Issue by abhineet09** [plantuml/plantuml-stdlib#45]
Diagrams generated using C4-plantuml library, doesn't render relationships when !pragma layout smetana is used

Sample notation:

```plantuml
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
!pragma layout smetana
System_Boundary(a, "a"){

    Container_Boundary(b, "b"){

          Component(c, "c", "xyz", "c")

   }
}

Person(d, "d")
Person(e, "e")

Rel(a, d, "a to d")
Rel(a, e, "a to e")
Rel(b, c, "b to c")
@enduml
```

Without Smetana layout: 

![raw](https://user-images.githubusercontent.com/58846915/130940227-e03fdc4d-62a3-4513-bc6b-6454dad8105f.PNG)

With Smetana Layout:

![Capture](https://user-images.githubusercontent.com/58846915/130940420-9ef64147-8196-4cbb-a5e1-762be7eb42f8.PNG)

**Comment by kirchsth** [comment]
Hi @abhineet09,

I'm not sure if smetana is maintained at all, maybe you test it with the elk layout.

```plantuml
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
!pragma layout elk
System_Boundary(a, "a"){

Container_Boundary(b, "b"){

      Component(c, "c", "xyz", "c")

}
}

Person(d, "d")
Person(e, "e")

Rel(a, d, "a to d")
Rel(a, e, "a to e")
Rel(b, c, "b to c")
@enduml
```
![](https://www.plantuml.com/plantuml/png/jOvFImCn4CNl-HHnJotOpSMJfsAl2aNnN2R9q2xcJqWcw2f-TsUMjNu2To5aVc_UUzatWaez1dKp9HUwHtqXAktUc0hlutcYIxUzONKv4IOQNOwc14ZYsJNoORBcSBSx2dfzUZGH6c5bT3gm0wQ4TIp_b1zBJknPyqk5SmGTOCwTD8OtzJBpRZmzv9uyr7a3jtg0OVkbrFLjVw9bqIwYNhvh_CQnuWO-FkRFORblbVhcNnsnjfmsdg5dk8x88yhECmRf51aqPIqxAyDVXYlZUkcnmgHWZydt67u0)

BR Helmut

**Comment by huornlmj** [comment]
Elk is an alpha feature, and results in this error with no diagram:
![image](https://user-images.githubusercontent.com/28444739/155382849-73b205b0-eb1a-43b0-b94c-2496f0ba0e71.png)

**Comment by kirchsth** [comment]
Do you have the problem with a local plantuml.jar file?
Does it work on the PlantUML server?

If it is a local problem:
Do you have elk-full.jar in the same folder as the plantuml.jar?
If not please add it and try it again (details see [Usage](https://plantuml.com/elk#Usage))

If it doesn't work on server too:
Can you add a sample.

BR Helmut

**Comment by kirchsth** [comment]
Hi all,

I checked it again, and smetana looks fixed in the meantime

[![](https://www.plantuml.com/plantuml/svg/jOv1ImCn48Nl-HLnJotOpSMJfsAl2aNnN2R9q2uaav1Cq5NyxqwMRVq5xaB8-zwyUTbNXi8j1dKtaGlDexumv_feJ86FyJpnfTbMiRX4ZCIZIz7a0DGpkye-JDOS7dR7ZjvVdas4obW4dGwIW8cmZFcVziUSI3Bh_bpW7447c5DZNICo4AYtMURZwIaryb3c3Tph0ORjjrAtz_sPLaoxc7hvRXKR9uuRvFYSluRblbK_ygiZbffeuuLvOQj4aIXIlMBebTq6pKdBp9NXbU7AfBtNsCwSi3sIRp7y0W00)](https://www.plantuml.com/plantuml/uml/jOv1ImCn48Nl-HLnJotOpSMJfsAl2aNnN2R9q2uaav1Cq5NyxqwMRVq5xaB8-zwyUTbNXi8j1dKtaGlDexumv_feJ86FyJpnfTbMiRX4ZCIZIz7a0DGpkye-JDOS7dR7ZjvVdas4obW4dGwIW8cmZFcVziUSI3Bh_bpW7447c5DZNICo4AYtMURZwIaryb3c3Tph0ORjjrAtz_sPLaoxc7hvRXKR9uuRvFYSluRblbK_ygiZbffeuuLvOQj4aIXIlMBebTq6pKdBp9NXbU7AfBtNsCwSi3sIRp7y0W00)

BR Helmut

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_ 👀 
This is now answered.
- Thanks @abhineet09  for the report.
- Thanks @kirchsth  for your answer.
- Thanks PlantUML team for your work.

Regards.
