### ISSUE TITLE
awslib/Mobile/Mobile.puml is black

### ISSUE THREAD

**Issue by StevusPrimus** [plantuml/plantuml-stdlib#63]
<img width="89" alt="image" src="https://user-images.githubusercontent.com/11518567/201474310-65817a0b-4331-45bc-853b-6c143248f177.png">

```
@startuml
!include <awslib/AWSCommon>
!include <awslib/Mobile/all.puml>

listsprites
@enduml
```

**Comment by The-Lum** [comment]
_Yes, You are right...._
Perhaps we could ask the question to the author of the changes.

@mmajis: We have some questions about your PR:
- https://github.com/plantuml/plantuml-stdlib/pull/46

On [`awslib/Mobile/Mobile.puml`](https://github.com/plantuml/plantuml-stdlib/blob/82a5108a2b773b6698f5a452d520fa0226f004dc/awslib/Mobile/Mobile.puml): 
- Do you know why the drawing of the mobile has disappeared?
- Does it due to the migration from v7.0 to v10.0 iconset?
- See diff.: https://github.com/plantuml/plantuml-stdlib/commit/82a5108a2b773b6698f5a452d520fa0226f004dc#diff-a0b8f17c697e59e363e40cf489b8d842b281d7c4cd945c7b7420948bc18fcdbb

Same question on [`awslib/Mobile/all.puml`](https://github.com/plantuml/plantuml-stdlib/blob/82a5108a2b773b6698f5a452d520fa0226f004dc/awslib/Mobile/all.puml):
- Do you know why all these changes?
- Why did you delete `APIGateway, APIGatewayEndpoint, Amplify, AppSync2, DeviceFarm, Pinpoint2, Pinpoint2Participant` and keep only `Mobile` and `MobileParticipant`?
- See diff.: https://github.com/plantuml/plantuml-stdlib/commit/82a5108a2b773b6698f5a452d520fa0226f004dc#diff-fb2293968dbd5e6c8d83993334bd5cf04324b88a57ff6b0323e4e2d9413d3601

_Thanks for your help,_
Regards.

**Comment by mmajis** [comment]
Hi!

Here's the upstream source for the iconset: https://github.com/awslabs/aws-icons-for-plantuml/tree/v10.0/dist

They have breaking changes between releases. In fact it looks like the entire Mobile folder is gone in v11.0 and also in the latest v14.0 release. The icons from the Mobile folder have moved around to different folders like ApplicationIntegration, BusinessApplications, FrontendWebMobile etc.

What happened here was that `Mobile.puml` and `all.puml` got overwritten by v10.0 but the other files from v7.0 were left over as they no longer exist in v10.0.

I was trying to avoid breaking old diagrams by leaving the files there but didn't realize that the `all.puml` imports were going to break for those icons anyway.

One way to clean up would be to remove all the leftover files that are now unreferenced from `all.puml` in each folder. That would further break diagrams that import the service-specific puml files but we'd stay fully in sync with the upstream iconset.

Another option is to start carefully managing the merging of `all.puml` files to maintain backwards compatibility when updating to newer upstream icons. That might escalate to a lot of work and duplication of icons in various folders in the stdlib iconset going forward.

Maybe a third option would be to maintain multiple versions of the AWS iconset in the stdlib with some sort of deprecation schedule for old versions?

**Comment by arnaudroques** [comment]
> Maybe a third option would be to maintain multiple versions of the AWS iconset in the stdlib with some sort of deprecation schedule for old versions?

I think it's the best solution.

So here what I suggest:

- Let's forget about v7.0
- Let's rename current `awslib` directory to `awslib10` and remove old v7.0 icons
- Let's create new `awslib14` directory with v14.0 icons
- We (the PlantUML team) will create a new system of internal symbolic links so that `awslib`  points to `awslib14` 

I am aware that we are breaking compatibility here, and that people may have to rename their `!include <awslib/...>` to `!include <awslib10/...>` and that older diagrams with v7.0 icons will also break.

However, in the future, people would be able to choose:

- either to stick to a specific version (using  `!include <awslib14/...>` for example )
- or use the last by default (using  `!include <awslib/...>` ) with a risk of issue when upgrading PlantUML version.

And when v15.0 will be released, we will simply create a new  `awslib15` directory and make `awslib` linking to it. 

Does it make sense?

**Comment by mmajis** [comment]
Sounds good!

**Comment by arnaudroques** [comment]
> Sounds good!

So `awslib` has been renamed to `awslib10`. And there is a new `awslib` pointing to `awslib10` now.

@mmajis Could you clean up `awslib10` and remove old v7.0 icons there?
If that's easy to do, you may also create a new `awslib14` with v14.0.

**Comment by mmajis** [comment]
Created PRs #64 for awslib10 cleanup and #65 to add awslib14.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_ 👀 
This is now fixed.
- Thanks @StevusPrimus for the report.
- Thanks PlantUML team, @Potherca and @mmajis for your work.

Regards.
